<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Chapter 11, Vignette 1: Background on the F distribution • RJafroc</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Chapter 11, Vignette 1: Background on the F distribution">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">RJafroc</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.1.1.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/QuickStartDBMH.html">Ch10: Quick Start: Running DBMH-ORH analysis</a>
    </li>
    <li>
      <a href="../articles/QuickStartDBMHExcelOutput.html">Ch10: Quick Start: DBMH-ORH Analysis Excel Output</a>
    </li>
    <li>
      <a href="../articles/SampleSizeCh11V1.html">Chapter 11, Vignette 1: Background on the F distribution</a>
    </li>
    <li>
      <a href="../articles/SampleSizeCh11V2.html">Chapter 11, Vignette 2: ROC-DBMH sample size from first principles</a>
    </li>
    <li>
      <a href="../articles/SampleSizeCh11V3.html">Chapter 11, Vignette 1: ROC sample size from first principles</a>
    </li>
    <li>
      <a href="../articles/SampleSizeROC.html">Chapter 11, Vignette 1: ROC sample size from first principles</a>
    </li>
    <li>
      <a href="../articles/cbmPlots.html">Ch20: CBM plots</a>
    </li>
    <li>
      <a href="../articles/degenerateROCs.html">Ch20: degenerate datasets in the binormal model</a>
    </li>
    <li>
      <a href="../articles/improperROCs.html">Ch20: improper ROCs</a>
    </li>
    <li>
      <a href="../articles/metzEqn36.html">Ch20: Metz Eqn36</a>
    </li>
    <li>
      <a href="../articles/proprocROCs.html">Ch20: proper ROCs and pdfs</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Chapter 11, Vignette 1: Background on the F distribution</h1>
                        <h4 class="author">Dev P. Chakraborty</h4>
            
            <h4 class="date">2018-11-22</h4>
      
      
      <div class="hidden name"><code>SampleSizeCh11V1.Rmd</code></div>

    </div>

    
    
<div id="illustrating-the-f-distribution" class="section level2">
<h2 class="hasAnchor">
<a href="#illustrating-the-f-distribution" class="anchor"></a>Illustrating the F-distribution</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ndf &lt;-<span class="st"> </span><span class="dv">1</span>;ddf &lt;-<span class="st"> </span><span class="dv">10</span>;ncp &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">0</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">10</span>)
fCrit &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Fdist">qf</a></span>(<span class="fl">0.95</span>, ndf,ddf)
<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cat">cat</a></span>(<span class="st">"critical value of x for rejecting NH is "</span>, fCrit,<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)
<span class="co">#&gt; critical value of x for rejecting NH is  4.964603</span>
x &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="dv">1</span>, <span class="dv">20</span>, <span class="fl">0.1</span>)
myLabel &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>, <span class="st">"D"</span>)
myLabelIndx &lt;-<span class="st"> </span><span class="dv">1</span>
<span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(ncp))
{
  y &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Fdist">df</a></span>(x,ndf,ddf,<span class="dt">ncp=</span>ncp[i])
  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cat">cat</a></span>(<span class="st">"ndf = "</span>, ndf, <span class="st">", ddf = "</span>, ddf, <span class="st">", ncp = "</span>, ncp[i], <span class="st">", prob &gt; fCrit = "</span>, 
      <span class="dv">1</span><span class="op">-</span><span class="kw"><a href="https://www.rdocumentation.org/packages/stats/topics/Fdist">pf</a></span>(fCrit, ndf, ddf, <span class="dt">ncp =</span> ncp[i]), <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)
  curveData &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">x =</span> x, <span class="dt">pdf =</span> y)
  curvePlot &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="dt">data =</span> curveData, <span class="dt">mapping =</span> <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> pdf)) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_line</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">ggtitle</span>(myLabel[myLabelIndx]);myLabelIndx &lt;-<span class="st"> </span>myLabelIndx <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/print">print</a></span>(curvePlot)
}
<span class="co">#&gt; ndf =  1 , ddf =  10 , ncp =  0 , prob &gt; fCrit =  0.05</span></code></pre></div>
<p><img src="SampleSizeCh11V1_files/figure-html/unnamed-chunk-1-1.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; ndf =  1 , ddf =  10 , ncp =  2 , prob &gt; fCrit =  0.2490518</code></pre>
<p><img src="SampleSizeCh11V1_files/figure-html/unnamed-chunk-1-2.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; ndf =  1 , ddf =  10 , ncp =  5 , prob &gt; fCrit =  0.5238753</code></pre>
<p><img src="SampleSizeCh11V1_files/figure-html/unnamed-chunk-1-3.png" width="700" style="display: block; margin: auto;"></p>
<pre><code>#&gt; ndf =  1 , ddf =  10 , ncp =  10 , prob &gt; fCrit =  0.8128068</code></pre>
<p><img src="SampleSizeCh11V1_files/figure-html/unnamed-chunk-1-4.png" width="700" style="display: block; margin: auto;"></p>
<div id="comments" class="section level3">
<h3 class="hasAnchor">
<a href="#comments" class="anchor"></a>Comments</h3>
<ol style="list-style-type: upper-alpha">
<li>Corresponds to <code>ncp = 0</code>, which yields the usual (aka <em>central</em>) F-distribution that was used in the previous two chapters (9 and 10). The integral under this distribution is unity (this is true for all plots above). The critical value, <code>fCrit</code> in the code, is that value of <code>x</code> such that the probability of exceeding <code>x</code> is <span class="math inline">\(\alpha\)</span>; in the current example <code>fCrit</code> = 4.9646027. Notice the use of the quantile function <code><a href="https://www.rdocumentation.org/packages/stats/topics/Fdist">qf()</a></code> to determine this value, also that the default value of <code>ncp</code>, namely zero, is used; specifically, one does not pass a 4th argument to <code><a href="https://www.rdocumentation.org/packages/stats/topics/Fdist">qf()</a></code>. <strong>The decision rule for rejecting the NH uses the NH distribution of the F-statistic</strong>, i.e., reject the NH if F &gt;= <code>fCrit</code>. As expected, <code>prob &gt; fCrit</code> = 0.05 because this is how <code>fCrit</code> was defined.</li>
<li>Corresponds to <code>ncp = 2</code>. It is noticeably shifted to the right as compared to A, thereby making it more likely that the observed value of the F-statistic will exceed the critical value determined for the NH distribution. In fact, <code>prob &gt; fCrit</code> = 0.2490518, which is the <em>statistical power</em>.</li>
<li>Corresponds to <code>ncp = 5</code>, and now <code>prob &gt; fCrit</code> = 0.5238753.</li>
<li>Corresponds to <code>ncp = 10</code>, and now <code>prob &gt; fCrit</code> is 0.8128068. The effect of the shift is obvious in plots (C) and (D). Considering a vertical line at <code>x = 4.10</code>, most of the distribution in plot (D), more than 0.8128068, to be precise, lies to the right of this line, so the NH is more than 0.8128068 likely to be rejected. Of course, what causes the shift is the increased value of the non-centrality parameter. The larger that non-centrality parameter, the greater the shift to the right.</li>
</ol>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#illustrating-the-f-distribution">Illustrating the F-distribution</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Dev Chakraborty, Xuetong Zhai.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.2.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
