# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BMNLLInner <- function(a, b, zetas, fi, ti) {
    .Call('_RJafroc_BMNLLInner', PACKAGE = 'RJafroc', a, b, zetas, fi, ti)
}

Qz <- function(zeta1, zeta2) {
    .Call('_RJafroc_Qz', PACKAGE = 'RJafroc', zeta1, zeta2)
}

Pz <- function(mu, alpha, zeta1, zeta2) {
    .Call('_RJafroc_Pz', PACKAGE = 'RJafroc', mu, alpha, zeta1, zeta2)
}

CBMNLLInner <- function(mu, alpha, zetas, fi, ti) {
    .Call('_RJafroc_CBMNLLInner', PACKAGE = 'RJafroc', mu, alpha, zetas, fi, ti)
}

HrSp <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_HrSp', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

ExpTrnsfmSp <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_ExpTrnsfmSp', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

MaxNLF <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_MaxNLF', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

MaxLLF <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_MaxLLF', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

TrapezoidalArea <- function(noise, n_noise, signal, n_signal) {
    .Call('_RJafroc_TrapezoidalArea', PACKAGE = 'RJafroc', noise, n_noise, signal, n_signal)
}

HrAuc <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_HrAuc', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

HrSe <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_HrSe', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

AFROC1 <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_AFROC1', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

AFROC <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_AFROC', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

wAFROC1 <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll, weights) {
    .Call('_RJafroc_wAFROC1', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll, weights)
}

wAFROC <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll, weights) {
    .Call('_RJafroc_wAFROC', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll, weights)
}

MaxNLFAllCases <- function(nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll) {
    .Call('_RJafroc_MaxNLFAllCases', PACKAGE = 'RJafroc', nl, ll, n_lesions_per_image, max_cases, max_nl, max_ll)
}

ROI <- function(ncases_nor, ncases_abn, max_nl, n_les, nl, ll) {
    .Call('_RJafroc_ROI', PACKAGE = 'RJafroc', ncases_nor, ncases_abn, max_nl, n_les, nl, ll)
}

SongA1 <- function(ncases_nor, ncases_abn, max_nl, max_ll, n_les, nl, ll) {
    .Call('_RJafroc_SongA1', PACKAGE = 'RJafroc', ncases_nor, ncases_abn, max_nl, max_ll, n_les, nl, ll)
}

SongA2 <- function(ncases_nor, ncases_abn, max_nl, max_ll, n_les, nl, ll) {
    .Call('_RJafroc_SongA2', PACKAGE = 'RJafroc', ncases_nor, ncases_abn, max_nl, max_ll, n_les, nl, ll)
}

erfcpp <- function(x) {
    .Call('_RJafroc_erfcpp', PACKAGE = 'RJafroc', x)
}

erfVect <- function(x) {
    .Call('_RJafroc_erfVect', PACKAGE = 'RJafroc', x)
}

xROC <- function(zeta, lambda) {
    .Call('_RJafroc_xROC', PACKAGE = 'RJafroc', zeta, lambda)
}

xROCVect <- function(zeta, lambda) {
    .Call('_RJafroc_xROCVect', PACKAGE = 'RJafroc', zeta, lambda)
}

yROC <- function(zeta, mu, lambda, nu, lesDistr) {
    .Call('_RJafroc_yROC', PACKAGE = 'RJafroc', zeta, mu, lambda, nu, lesDistr)
}

yROCVect <- function(zeta, mu, lambda, nu, lesDistr) {
    .Call('_RJafroc_yROCVect', PACKAGE = 'RJafroc', zeta, mu, lambda, nu, lesDistr)
}

RsmInner <- function(mu, lambda, nu, lesDistr, zeta, fb, tb) {
    .Call('_RJafroc_RsmInner', PACKAGE = 'RJafroc', mu, lambda, nu, lesDistr, zeta, fb, tb)
}

y_ROC_FPF <- function(FPF, mu, lambda, nu, lesDistr) {
    .Call('_RJafroc_y_ROC_FPF', PACKAGE = 'RJafroc', FPF, mu, lambda, nu, lesDistr)
}

RSM_wLLF <- function(zeta, mu, nu, f_L, W) {
    .Call('_RJafroc_RSM_wLLF', PACKAGE = 'RJafroc', zeta, mu, nu, f_L, W)
}

ForwardValue <- function(value, valueLower, valueUpper) {
    .Call('_RJafroc_ForwardValue', PACKAGE = 'RJafroc', value, valueLower, valueUpper)
}

InverseValue <- function(valueFwd, valueLower, valueUpper) {
    .Call('_RJafroc_InverseValue', PACKAGE = 'RJafroc', valueFwd, valueLower, valueUpper)
}

